/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param typeDisplay 
 * @param id 
 * @param timestamp 
 * @param commandId 
 * @param additionalData 
 */


data class AlertHistory (

    @Json(name = "type")
    val type: kotlin.Int,

    @Json(name = "type_display")
    val typeDisplay: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime? = null,

    @Json(name = "command_id")
    val commandId: kotlin.Int? = null,

    @Json(name = "additional_data")
    val additionalData: kotlin.String? = null,

    @Json(name = "car")
    val car: Car? = null

) {


}

