/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.EVInfo
import org.openapitools.client.models.LocationInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param vin 
 * @param evInfo 
 * @param location 
 * @param lastConnection 
 * @param nickname 
 */


data class CarSerializerList (

    @Json(name = "vin")
    val vin: kotlin.String,

    @Json(name = "ev_info")
    val evInfo: EVInfo,

    @Json(name = "location")
    val location: LocationInfo,

    @Json(name = "last_connection")
    val lastConnection: java.time.OffsetDateTime? = null,

    @Json(name = "nickname")
    val nickname: kotlin.String? = null,

    @Json(name = "carrier")
    val carrier: kotlin.String? = null,

    @Json(name = "signalLevel")
    val signalLevel: kotlin.Int? = null

) {


}

