/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.EVInfoUpdating
import org.openapitools.client.models.RoutePlan
import org.openapitools.client.models.SendToCarLocation

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sendToCarLocation 
 * @param sendToCarLocationAll 
 * @param evInfo 
 * @param routePlans 
 * @param favoriteChannels 
 * @param customChannels 
 */


data class CarUpdating (

    @Json(name = "send_to_car_location")
    var sendToCarLocation: SendToCarLocation? = null,

    @Json(name = "send_to_car_location_all")
    val sendToCarLocationAll: kotlin.collections.List<SendToCarLocation>? = null,

    @Json(name = "ev_info")
    val evInfo: EVInfoUpdating? = null,

    @Json(name = "route_plans")
    val routePlans: kotlin.collections.List<RoutePlan>? = null,

    @Json(name = "favorite_channels")
    val favoriteChannels: kotlin.Any? = null,

    @Json(name = "custom_channels")
    val customChannels: kotlin.Any? = null

) {


}

