/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param time 
 * @param id 
 * @param commandTypeDisplay 
 * @param lastCommandResultDisplay 
 * @param timerTypeDisplay 
 * @param enabled 
 * @param timerType 
 * @param commandType 
 * @param lastCommandResult 
 * @param lastCommandExecution 
 * @param weekdayMon 
 * @param weekdayTue 
 * @param weekdayWed 
 * @param weekdayThu 
 * @param weekdayFri 
 * @param weekdaySat 
 * @param weekdaySun 
 * @param date 
 */


data class CommandTimerSetting (

    @Json(name = "name")
    var name: kotlin.String,

    @Json(name = "time")
    var time: kotlin.String,

    @Json(name = "id")
    var id: kotlin.Int? = null,

    @Json(name = "command_type_display")
    val commandTypeDisplay: kotlin.String? = null,

    @Json(name = "last_command_result_display")
    val lastCommandResultDisplay: kotlin.String? = null,

    @Json(name = "timer_type_display")
    val timerTypeDisplay: kotlin.String? = null,

    @Json(name = "enabled")
    var enabled: kotlin.Boolean? = null,

    @Json(name = "timer_type")
    var timerType: kotlin.Int? = null,

    @Json(name = "command_type")
    var commandType: kotlin.Int? = null,

    @Json(name = "last_command_result")
    val lastCommandResult: kotlin.Int? = null,

    @Json(name = "last_command_execution")
    val lastCommandExecution: java.time.OffsetDateTime? = null,

    @Json(name = "weekday_mon")
    var weekdayMon: kotlin.Boolean? = null,

    @Json(name = "weekday_tue")
    var weekdayTue: kotlin.Boolean? = null,

    @Json(name = "weekday_wed")
    var weekdayWed: kotlin.Boolean? = null,

    @Json(name = "weekday_thu")
    var weekdayThu: kotlin.Boolean? = null,

    @Json(name = "weekday_fri")
    var weekdayFri: kotlin.Boolean? = null,

    @Json(name = "weekday_sat")
    var weekdaySat: kotlin.Boolean? = null,

    @Json(name = "weekday_sun")
    var weekdaySun: kotlin.Boolean? = null,

    @Json(name = "date")
    var date: java.time.LocalDate? = null

) {


}

