/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param rangeAcon 
 * @param rangeAcoff 
 * @param pluggedIn 
 * @param charging 
 * @param chargeFinish 
 * @param quickCharging 
 * @param acStatus 
 * @param chargeBars 
 * @param carRunning 
 * @param carGear 
 * @param ecoMode 
 * @param soh 
 * @param soc 
 * @param socDisplay 
 * @param whContent 
 * @param capBars 
 * @param gids 
 * @param counter 
 * @param maxGids 
 * @param fullChgTime 
 * @param limitChgTime 
 * @param obc6kw 
 * @param param21 
 * @param forceSocDisplay 
 * @param obc6kwAvail 
 * @param battHeaterAvail 
 * @param battHeaterStatus 
 * @param lastUpdated 
 */


data class EVInfo (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "range_acon")
    val rangeAcon: kotlin.Int? = null,

    @Json(name = "range_acoff")
    val rangeAcoff: kotlin.Int? = null,

    @Json(name = "plugged_in")
    val pluggedIn: kotlin.Boolean? = null,

    @Json(name = "charging")
    val charging: kotlin.Boolean? = null,

    @Json(name = "charge_finish")
    val chargeFinish: kotlin.Boolean? = null,

    @Json(name = "quick_charging")
    val quickCharging: kotlin.Boolean? = null,

    @Json(name = "ac_status")
    val acStatus: kotlin.Boolean? = null,

    @Json(name = "charge_bars")
    val chargeBars: kotlin.Int? = null,

    @Json(name = "car_running")
    val carRunning: kotlin.Boolean? = null,

    @Json(name = "car_gear")
    val carGear: kotlin.Int? = null,

    @Json(name = "eco_mode")
    val ecoMode: kotlin.Boolean? = null,

    @Json(name = "soh")
    val soh: kotlin.Int? = null,

    @Json(name = "soc")
    val soc: java.math.BigDecimal? = null,

    @Json(name = "soc_display")
    val socDisplay: java.math.BigDecimal? = null,

    @Json(name = "wh_content")
    val whContent: java.math.BigDecimal? = null,

    @Json(name = "cap_bars")
    val capBars: kotlin.Int? = null,

    @Json(name = "gids")
    val gids: kotlin.Int? = null,

    @Json(name = "counter")
    val counter: kotlin.Int? = null,

    @Json(name = "max_gids")
    val maxGids: kotlin.Int? = null,

    @Json(name = "full_chg_time")
    val fullChgTime: kotlin.Int? = null,

    @Json(name = "limit_chg_time")
    val limitChgTime: kotlin.Int? = null,

    @Json(name = "obc_6kw")
    val obc6kw: kotlin.Int? = null,

    @Json(name = "param21")
    val param21: kotlin.Int? = null,

    @Json(name = "force_soc_display")
    val forceSocDisplay: kotlin.Boolean? = null,

    @Json(name = "obc_6kw_avail")
    val obc6kwAvail: kotlin.Boolean? = null,

    @Json(name = "batt_heater_avail")
    val battHeaterAvail: kotlin.Boolean? = null,

    @Json(name = "batt_heater_status")
    val battHeaterStatus: kotlin.Boolean? = null,

    @Json(name = "last_updated")
    val lastUpdated: java.time.OffsetDateTime? = null

) {


}

