/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param lat 
 * @param lon 
 * @param home 
 * @param lastUpdated 
 */


data class LocationInfo (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "lat")
    val lat: java.math.BigDecimal? = null,

    @Json(name = "lon")
    val lon: java.math.BigDecimal? = null,

    @Json(name = "home")
    val home: kotlin.Boolean? = null,

    @Json(name = "last_updated")
    val lastUpdated: java.time.OffsetDateTime? = null

) {


}

