/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status
 * @param cause
 * @param location
 */


data class MapLinkResolverResponse (

    @Json(name = "status")
    val status: Boolean,

    @Json(name = "cause")
    val cause: String? = null,

    @Json(name = "location")
    val location: MapLinkResolvedLocation? = null

) {


}

