/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param lat 
 * @param lon 
 * @param name 
 * @param address 
 */


data class MapLinkResolvedLocation (

    @Json(name = "lat")
    val lat: java.math.BigDecimal,

    @Json(name = "lon")
    val lon: java.math.BigDecimal,

    @Json(name = "name")
    val name: String? = null,

    @Json(name = "address")
    val address: String? = null,

) {


}

