/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param startName 
 * @param startLat 
 * @param startLon 
 * @param finishName 
 * @param finishLat 
 * @param finishLon 
 * @param id 
 * @param point1Name 
 * @param point1Lat 
 * @param point1Lon 
 * @param point2Name 
 * @param point2Lat 
 * @param point2Lon 
 * @param point3Name 
 * @param point3Lat 
 * @param point3Lon 
 * @param point4Name 
 * @param point4Lat 
 * @param point4Lon 
 * @param point5Name 
 * @param point5Lat 
 * @param point5Lon 
 * @param createdAt 
 */


data class RoutePlan (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "start_name")
    val startName: kotlin.String,

    @Json(name = "start_lat")
    val startLat: java.math.BigDecimal,

    @Json(name = "start_lon")
    val startLon: java.math.BigDecimal,

    @Json(name = "finish_name")
    val finishName: kotlin.String,

    @Json(name = "finish_lat")
    val finishLat: java.math.BigDecimal,

    @Json(name = "finish_lon")
    val finishLon: java.math.BigDecimal,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "point1_name")
    val point1Name: kotlin.String? = null,

    @Json(name = "point1_lat")
    val point1Lat: java.math.BigDecimal? = null,

    @Json(name = "point1_lon")
    val point1Lon: java.math.BigDecimal? = null,

    @Json(name = "point2_name")
    val point2Name: kotlin.String? = null,

    @Json(name = "point2_lat")
    val point2Lat: java.math.BigDecimal? = null,

    @Json(name = "point2_lon")
    val point2Lon: java.math.BigDecimal? = null,

    @Json(name = "point3_name")
    val point3Name: kotlin.String? = null,

    @Json(name = "point3_lat")
    val point3Lat: java.math.BigDecimal? = null,

    @Json(name = "point3_lon")
    val point3Lon: java.math.BigDecimal? = null,

    @Json(name = "point4_name")
    val point4Name: kotlin.String? = null,

    @Json(name = "point4_lat")
    val point4Lat: java.math.BigDecimal? = null,

    @Json(name = "point4_lon")
    val point4Lon: java.math.BigDecimal? = null,

    @Json(name = "point5_name")
    val point5Name: kotlin.String? = null,

    @Json(name = "point5_lat")
    val point5Lat: java.math.BigDecimal? = null,

    @Json(name = "point5_lon")
    val point5Lon: java.math.BigDecimal? = null,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null

) {


}

