/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal
import java.time.OffsetDateTime

/**
 * 
 *
 * @param id 
 * @param lat 
 * @param lon 
 * @param name
 */


data class SendToCarLocation (

    @Json(name = "id")
    val id: Int? = null,

    @Json(name = "lat")
    var lat: BigDecimal? = null,

    @Json(name = "lon")
    var lon: BigDecimal? = null,

    @Json(name = "name")
    var name: String? = null,

) {


}

