/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param lat 
 * @param lon 
 * @param name 
 * @param id 
 * @param createdAt 
 */


data class SendToCarLocation (

    @Json(name = "lat")
    val lat: java.math.BigDecimal,

    @Json(name = "lon")
    val lon: java.math.BigDecimal,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null

) {


}

