/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param refresh 
 * @param access 
 */


data class TokenRefreshResponse (

    @Json(name = "access")
    val access: kotlin.String,

    @Json(name = "refresh")
    val refresh: kotlin.String? = null

) {


}

