/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.EVInfo
import org.openapitools.client.models.LocationInfo
import org.openapitools.client.models.TCUConfiguration

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param tcuConfiguration 
 * @param location 
 * @param evInfo 
 * @param commandTypeDisplay 
 * @param commandResultDisplay 
 * @param vin 
 * @param smsConfig 
 * @param owner 
 * @param id 
 * @param nickname 
 * @param color 
 * @param vehicleCode1 
 * @param vehicleCode2 
 * @param vehicleCode3 
 * @param vehicleCode4 
 * @param tcuModel 
 * @param tcuSerial 
 * @param iccid 
 * @param tcuVer 
 * @param tcuUser 
 * @param tcuPass 
 * @param disableAuth 
 * @param lastConnection 
 * @param periodicRefresh 
 * @param periodicRefreshRunning 
 * @param commandId 
 * @param commandResult 
 * @param commandRequested 
 * @param commandPayload 
 * @param commandType 
 * @param commandRequestTime 
 */


data class Car (

    @Json(name = "tcu_configuration")
    val tcuConfiguration: TCUConfiguration,

    @Json(name = "location")
    val location: LocationInfo,

    @Json(name = "ev_info")
    val evInfo: EVInfo,

    @Json(name = "command_type_display")
    val commandTypeDisplay: kotlin.String,

    @Json(name = "command_result_display")
    val commandResultDisplay: kotlin.String,

    @Json(name = "vin")
    val vin: kotlin.String,

    @Json(name = "sms_config")
    val smsConfig: kotlin.Any,

    @Json(name = "owner")
    val owner: kotlin.Int,

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "nickname")
    val nickname: kotlin.String? = null,

    @Json(name = "color")
    val color: Car.Color? = null,

    @Json(name = "vehicle_code1")
    val vehicleCode1: kotlin.Int? = null,

    @Json(name = "vehicle_code2")
    val vehicleCode2: kotlin.Int? = null,

    @Json(name = "vehicle_code3")
    val vehicleCode3: kotlin.Int? = null,

    @Json(name = "vehicle_code4")
    val vehicleCode4: kotlin.Int? = null,

    @Json(name = "tcu_model")
    val tcuModel: kotlin.String? = null,

    @Json(name = "tcu_serial")
    val tcuSerial: kotlin.String? = null,

    @Json(name = "iccid")
    val iccid: kotlin.String? = null,

    @Json(name = "tcu_ver")
    val tcuVer: kotlin.String? = null,

    @Json(name = "tcu_user")
    val tcuUser: kotlin.String? = null,

    @Json(name = "tcu_pass")
    val tcuPass: kotlin.String? = null,

    @Json(name = "disable_auth")
    val disableAuth: kotlin.Boolean? = null,

    @Json(name = "last_connection")
    val lastConnection: java.time.OffsetDateTime? = null,

    @Json(name = "periodic_refresh")
    val periodicRefresh: kotlin.Int? = null,

    @Json(name = "periodic_refresh_running")
    val periodicRefreshRunning: kotlin.Int? = null,

    @Json(name = "command_id")
    val commandId: kotlin.Int? = null,

    @Json(name = "command_result")
    val commandResult: kotlin.Int? = null,

    @Json(name = "command_requested")
    val commandRequested: kotlin.Boolean? = null,

    @Json(name = "command_payload")
    val commandPayload: kotlin.Any? = null,

    @Json(name = "command_type")
    val commandType: kotlin.Int? = null,

    @Json(name = "command_request_time")
    val commandRequestTime: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: l_coulisred,l_deepblue,l_forgedbronze,l_gunmetallic,l_pearlwhite,l_planetblue,l_superblack,env200_white
     */
    @JsonClass(generateAdapter = false)
    enum class Color(val value: kotlin.String) {
        @Json(name = "l_coulisred") l_coulisred("l_coulisred"),
        @Json(name = "l_deepblue") l_deepblue("l_deepblue"),
        @Json(name = "l_forgedbronze") l_forgedbronze("l_forgedbronze"),
        @Json(name = "l_gunmetallic") l_gunmetallic("l_gunmetallic"),
        @Json(name = "l_pearlwhite") l_pearlwhite("l_pearlwhite"),
        @Json(name = "l_planetblue") l_planetblue("l_planetblue"),
        @Json(name = "l_superblack") l_superblack("l_superblack"),
        @Json(name = "env200_white") env200_white("env200_white");
    }

}

