/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param username 
 * @param password 
 * @param deviceType 
 * @param deviceOs 
 * @param appVersion 
 * @param pushNotificationKey 
 */


data class JWTTokenObtainPair (

    @Json(name = "username")
    val username: kotlin.String,

    @Json(name = "password")
    val password: kotlin.String,

    @Json(name = "device_type")
    val deviceType: kotlin.String? = null,

    @Json(name = "device_os")
    val deviceOs: kotlin.String? = null,

    @Json(name = "app_version")
    val appVersion: kotlin.String? = null,

    @Json(name = "push_notification_key")
    val pushNotificationKey: kotlin.String? = null

) {


}

