/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param dialCode 
 * @param apn 
 * @param apnUser 
 * @param apnPassword 
 * @param dns1 
 * @param dns2 
 * @param serverUrl 
 * @param proxyUrl 
 * @param connectionType 
 * @param lastUpdated 
 */


data class TCUConfiguration (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "dial_code")
    val dialCode: kotlin.String? = null,

    @Json(name = "apn")
    val apn: kotlin.String? = null,

    @Json(name = "apn_user")
    val apnUser: kotlin.String? = null,

    @Json(name = "apn_password")
    val apnPassword: kotlin.String? = null,

    @Json(name = "dns1")
    val dns1: kotlin.String? = null,

    @Json(name = "dns2")
    val dns2: kotlin.String? = null,

    @Json(name = "server_url")
    val serverUrl: kotlin.String? = null,

    @Json(name = "proxy_url")
    val proxyUrl: kotlin.String? = null,

    @Json(name = "connection_type")
    val connectionType: kotlin.String? = null,

    @Json(name = "last_updated")
    val lastUpdated: java.time.OffsetDateTime? = null

) {


}

